### ISSUE TITLE
크롤링 엔진 DB 설계

### ISSUE THREAD

**Issue by wasuphj** [crazyinvestor/crazyinvestor#27]

**Comment by wasuphj** [comment]
- Ticker Metadata (티커 메타데이터 / 거래소-심볼-티커타입 등)
- Ticker History (받아온 티커 로그)
- Quote Data (현재 가격)
- OrderBook History (호가창 갱신 로그)
- OrderBook Data (현재 호가창)
- Transaction History (거래 체결 데이터)
- Recent Trasnaction (최근 거래 10-100개)

**Comment by wasuphj** [comment]
https://www.erdcloud.com/d/NtK86ydG5rtEMqfeh

**Comment by limdongjin** [comment]
#59 denormalization 고도화 필요
