### ISSUE TITLE
Spring Redis 캐싱 기능 사용

### ISSUE THREAD

**Issue by wasuphj** [crazyinvestor/crazyinvestor#30]

**Comment by limdongjin** [comment]
캐싱을 하는 범위는 어느정도로 생각하고 있나요? (ex, n분 이내 최신 정보)
기대가능한 긍정적 효과, 우려되는 문제가 있을까요?

**Comment by wasuphj** [comment]
현재 받은 모든 데이터를 모두 RDB에 저장하는 구조로 시작하고 있는데, Quote 테이블에서 update를 반복하는 구조로 되어있어 이에 따른 IO 성능 저하가 우려됩니다.

해결책으로 생각 중인게 일단 아예 현재 시세에 대한 부분은 
 - 현재 구조에서 인덱스와 JPA 캐시 기능을 최대한 활용해 보는 방법
 - Event 방식으로 뿌리고 현재 시세 정보는 그냥 저장하지 않는 방법
 - Event 방식으로 뿌리고 저장 주기를 줄이는 방법

을 고려하고 있고, Redis 캐싱의 경우 첫 번째 방법에 유효할 것 같습니다.

**Comment by wasuphj** [comment]
다만, 쓰기 성능에 대해서는 큰 효과가 없을 것 같아서 아마 2번이나 3번 방법 방향으로 가야되지 않을까 싶네요 ㅎㅎ..

**Comment by wasuphj** [comment]
불필요하다고 판단되어 Close
